fix: handle 'git fetch' error if fetching into non-shallow local repo

diff --git a/delete-old-branches b/delete-old-branches
--- a/delete-old-branches
+++ b/delete-old-branches
@@ -125,7 +125,15 @@ main() {
     # fetch history etc
     local sha
     git config --global --add safe.directory "${GITHUB_WORKSPACE}"
-    git fetch --prune --unshallow --tags
+    echo "Fetching branches and tags..."
+    # catch error for git fetch with --unshallow if complete repo clone
+    if ! git fetch --prune --unshallow --tags origin '+refs/heads/*:refs/remotes/origin/*'; then
+        echo "Error: Failed to fetch branches and tags. This is likely because the repository is a complete clone."
+
+        echo "Re-fetching without --unshallow..."
+        git fetch --prune --tags origin '+refs/heads/*:refs/remotes/origin/*'
+    fi
+    echo "Checking branches..."
     for br in $(git ls-remote -q --heads --refs | sed "s@^.*heads/@@"); do
         if [[ -z "$(git log --oneline -1 --since="${DATE}" origin/"${br}")" ]]; then
             sha=$(git show-ref -s "origin/${br}")
